import os
import sys
import re

# Add the parent directory to sys.path to access src.bom_lib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.bom_lib import parse_pedalpcb_pdf, parse_csv_bom, InventoryType

INPUT_DIR = "raw_boms"
OUTPUT_FILE = "src/presets.py"


def natural_sort_key(ref_str):
    match = re.match(r"([a-zA-Z]+)(\d+)", ref_str)
    if match:
        return match.group(1), int(match.group(2))
    return ref_str, 0


def flatten_inventory_to_text(inventory: InventoryType) -> str:
    lines = []
    for key, data in inventory.items():
        if " | " in key:
            _, val = key.split(" | ", 1)
        else:
            val = key

        if not data["refs"]:
            continue

        for ref in data["refs"]:
            # Filter out hardware/injected parts
            if ref in ["HW", "PCB", "(Inj)"] or "Inj" in ref:
                continue
            lines.append((ref, val))

    lines.sort(key=lambda x: natural_sort_key(x[0]))
    return "\n".join([f"{r} {v}" for r, v in lines])


def generate_presets():
    if not os.path.exists(INPUT_DIR):
        os.makedirs(INPUT_DIR)
        print(f"Created directory '{INPUT_DIR}'. Drop files there.")
        return

    presets = {}
    report = []  # List of (Filename, Status, Details)

    files = sorted(os.listdir(INPUT_DIR))
    print(f"🔍 Found {len(files)} files in {INPUT_DIR}...")

    for filename in files:
        filepath = os.path.join(INPUT_DIR, filename)
        name, ext = os.path.splitext(filename)
        inventory = None
        status = "Unknown"
        details = ""

        try:
            # 1. Parse
            if ext.lower() == ".pdf":
                inventory, stats = parse_pedalpcb_pdf(filepath, "ingest")

                if stats["parts_found"] == 0:
                    status = "Skipped"
                    # Capture the last few residuals to see what happened
                    res_msg = (
                        "; ".join(stats["residuals"][-3:])
                        if stats["residuals"]
                        else "No parts found"
                    )
                    details = f"{res_msg}"
                else:
                    status = "Parsed"

            elif ext.lower() == ".csv":
                inventory, stats = parse_csv_bom(filepath, "ingest")
                status = "Parsed"

            else:
                status = "Ignored"
                details = f"Unsupported extension: {ext}"

            # 2. Process
            if status == "Parsed" and inventory:
                clean_text = flatten_inventory_to_text(inventory)

                if not clean_text.strip():
                    status = "Skipped"
                    details = "Inventory resulted in empty text"
                else:
                    display_name = name.replace("_", " ").title()
                    if display_name in presets:
                        status = "Warning"
                        details = "Overwrote existing preset"
                    else:
                        status = "Success"
                        details = f"{len(clean_text.splitlines())} lines"

                    presets[display_name] = clean_text

        except Exception as e:
            status = "Error"
            details = str(e)

        report.append((filename, status, details))
        print(f"   [{status}] {filename}")

    # --- WRITE TO FILE ---
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by tools/generate_presets.py\n")
        f.write("BOM_PRESETS = {\n")
        for name, text in presets.items():
            indented = text.replace("\n", "\n        ")
            f.write(f'    "{name}": """\n        {indented}\n    """,\n')
        f.write("}\n")

    # --- FINAL REPORT ---
    print("\n" + "=" * 60)
    print(f"  GENERATION REPORT: {len(presets)} Presets Created")
    print("=" * 60)
    print(f"{'FILENAME':<30} | {'STATUS':<10} | {'DETAILS'}")
    print("-" * 60)
    for fname, stat, det in report:
        print(f"{fname:<30} | {stat:<10} | {det}")
    print("=" * 60)


if __name__ == "__main__":
    generate_presets()
