import os
import sys

# Add the parent directory to sys.path to access src.bom_lib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.bom_lib import parse_pedalpcb_pdf, sort_inventory

INPUT_DIR = "raw_boms"
OUTPUT_FILE = "src/presets.py"


def serialize_inventory(inventory):
    """
    Converts the parsed dictionary back into the string format app.py expects.
    e.g. {'Resistors | 10k': refs=['R1', 'R2']} -> "R1 10k\nR2 10k"
    """
    lines = []

    # helper to clean the value (remove " | " prefix)
    def get_val(key):
        if " | " in key:
            return key.split(" | ", 1)[1]
        return key

    # Sort so the output text is tidy
    sorted_items = sort_inventory(inventory)

    for key, data in sorted_items:
        clean_val = get_val(key)

        # If we have specific refs (R1, C1), list them individually
        if data["refs"]:
            for ref in data["refs"]:
                # Ignore generic hardware refs if they slipped in
                if ref != "HW":
                    lines.append(f"{ref} {clean_val}")
        else:
            # Fallback for things without refs (rare in presets)
            lines.append(f"{clean_val} (Qty: {data['qty']})")

    return "\n".join(lines)


def generate_presets():
    if not os.path.exists(INPUT_DIR):
        os.makedirs(INPUT_DIR)
        print(f"Created directory '{INPUT_DIR}'.")
        # Don't return, user might have nested folders

    presets = {}

    print(f"🔍 Scanning {INPUT_DIR}...")

    for root, dirs, files in os.walk(INPUT_DIR):
        for file in files:
            file_path = os.path.join(root, file)
            filename_no_ext = os.path.splitext(file)[0]

            # 1. Determine Metadata from Folder Structure
            # rel_path: "pedalpcb/fuzz"
            rel_path = os.path.relpath(root, INPUT_DIR)
            path_parts = rel_path.split(os.sep)

            # Handle root files safely
            if rel_path == ".":
                path_parts = ["Misc"]

            # Construct a clean Key: "[Source] [Category] Name"
            # Format: "PedalPCB - Fuzz - Big Muff"
            source = path_parts[0].capitalize() if path_parts else "Unsorted"
            category = path_parts[1].capitalize() if len(path_parts) > 1 else ""

            # Build the Display Key
            if category:
                key = f"[{source}] [{category}] {filename_no_ext}"
            else:
                key = f"[{source}] {filename_no_ext}"

            # 2. Process File
            final_text = ""

            if file.lower().endswith(".txt"):
                # CASE A: Tayda / Raw Text
                # Trust the user's formatting (app.py verifies it anyway)
                with open(file_path, "r", encoding="utf-8") as f:
                    final_text = f.read()
                    print(f"   📄 Read Text: {file}")

            elif file.lower().endswith(".pdf"):
                # CASE B: PedalPCB PDF
                # Parse it, then serialize it back to text
                print(f"   ⚙️ Parsing PDF: {file}")
                try:
                    # We use the key as the source_name
                    inv, stats = parse_pedalpcb_pdf(file_path, source_name=key)

                    if stats["parts_found"] > 0:
                        final_text = serialize_inventory(inv)
                    else:
                        print(f"   ⚠️ Skipping {file}: No parts found.")
                        continue
                except Exception as e:
                    print(f"   ❌ Error parsing {file}: {e}")
                    continue

            # 3. Add to Dict
            if final_text:
                presets[key] = final_text

    # 4. Write Output
    print(f"💾 Writing {len(presets)} presets to {OUTPUT_FILE}...")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by tools/generate_presets.py\n")
        f.write("# DO NOT EDIT MANUALLY\n\n")
        f.write("BOM_PRESETS = {\n")

        # Sort keys for stability
        for k in sorted(presets.keys()):
            # Use triple quotes for readable multi-line strings
            # Indent the content by 8 spaces to match the dict structure
            content = presets[k].strip().replace("\n", "\n        ")
            f.write(f'    {repr(k)}: """\n        {content}\n    """,\n')

        f.write("}\n")

    print("✅ Done!")


if __name__ == "__main__":
    generate_presets()
