import os
import sys
import re

# Add the parent directory to sys.path to access src.bom_lib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.bom_lib import parse_pedalpcb_pdf, parse_csv_bom, InventoryType

INPUT_DIR = "raw_boms"
OUTPUT_FILE = "src/presets.py"


def natural_sort_key(ref_str):
    match = re.match(r"([a-zA-Z]+)(\d+)", ref_str)
    if match:
        return match.group(1), int(match.group(2))
    return ref_str, 0


def flatten_inventory_to_text(inventory: InventoryType) -> str:
    lines = []
    for key, data in inventory.items():
        if " | " in key:
            _, val = key.split(" | ", 1)
        else:
            val = key

        if not data["refs"]:
            continue

        for ref in data["refs"]:
            if ref in ["HW", "PCB", "(Inj)"] or "Inj" in ref:
                continue
            lines.append((ref, val))

    lines.sort(key=lambda x: natural_sort_key(x[0]))
    return "\n".join([f"{r} {v}" for r, v in lines])


def generate_presets():
    if not os.path.exists(INPUT_DIR):
        os.makedirs(INPUT_DIR)
        print(f"Created directory '{INPUT_DIR}'. Drop files there.")
        return

    presets = {}
    files = sorted(os.listdir(INPUT_DIR))

    for filename in files:
        filepath = os.path.join(INPUT_DIR, filename)
        name, ext = os.path.splitext(filename)
        inventory = None

        try:
            if ext.lower() == ".pdf":
                inventory, _ = parse_pedalpcb_pdf(filepath, "ingest")
            elif ext.lower() == ".csv":
                inventory, _ = parse_csv_bom(filepath, "ingest")

            if inventory:
                clean_text = flatten_inventory_to_text(inventory)

                if not clean_text.strip():
                    print(
                        f"      ⚠️  Warning: {filename} resulted in empty BOM. Skipping."
                    )
                    continue

                display_name = name.replace("_", " ").title()
                presets[display_name] = clean_text
                print(f"Processed: {display_name}")

        except Exception as e:
            print(f"Error {filename}: {e}")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by tools/generate_presets.py\n")
        f.write("BOM_PRESETS = {\n")
        for name, text in presets.items():
            indented = text.replace("\n", "\n        ")
            f.write(f'    "{name}": """\n        {indented}\n    """,\n')
        f.write("}\n")
    print("Done.")


if __name__ == "__main__":
    generate_presets()
